In [1]:
import pandas as pd
df=pd.read_csv("student_performance.csv", index_col="S_No")
print("\nOriginal Dataset:\n")
df

Original Dataset:

,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score,Result
S_No,,,,,,,,,,
1,Aastha,Female,19,CSE,92.0,6.5,18,27.0,88,Pass
2,Amrutha,Female,20,CSE,88.0,6.0,17,26.0,84,Pass
3,Shivam,Male,19,ECE,75.0,4.5,14,21.0,66,Pass
4,Usha,Female,21,ECE,82.0,5.0,16,23.0,72,Pass
5,Anusha,Female,20,CSE,68.0,3.0,12,NaN,52,Pass
6,Adarsh,Male,21,EEE,60.0,2.0,10,15.0,41,Fail
7,Karan,Male,20,ECE,NaN,4.0,13,20.0,61,Pass
8,Ansh,Male,19,EEE,65.0,2.5,11,17.0,48,Fail
9,Likhita,Female,20,CSE,95.0,7.5,19,29.0,93,Pass
10,Neha,Female,19,ECE,85.0,5.5,16,24.0,78,Pass
11,Laalitya,Female,21,EEE,78.0,4.8,15,NaN,70,Pass
12,Anvi,Female,20,CSE,90.0,6.8,18,28.0,86,Pass
13,Likhita,Female,20,CSE,95.0,7.5,19,29.0,93,Pass
14,Anvi,Female,20,CSE,90.0,6.8,18,28.0,86,Pass

In [2]:
print("\nFirst five records:\n")
df.head()

First five records:

,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score,Result
S_No,,,,,,,,,,
1,Aastha,Female,19,CSE,92.0,6.5,18,27.0,88,Pass
2,Amrutha,Female,20,CSE,88.0,6.0,17,26.0,84,Pass
3,Shivam,Male,19,ECE,75.0,4.5,14,21.0,66,Pass
4,Usha,Female,21,ECE,82.0,5.0,16,23.0,72,Pass
5,Anusha,Female,20,CSE,68.0,3.0,12,NaN,52,Pass

In [3]:
print("\nLast five records:\n")
df.tail()

Last five records:

,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score,Result
S_No,,,,,,,,,,
10,Neha,Female,19,ECE,85.0,5.5,16,24.0,78,Pass
11,Laalitya,Female,21,EEE,78.0,4.8,15,NaN,70,Pass
12,Anvi,Female,20,CSE,90.0,6.8,18,28.0,86,Pass
13,Likhita,Female,20,CSE,95.0,7.5,19,29.0,93,Pass
14,Anvi,Female,20,CSE,90.0,6.8,18,28.0,86,Pass

In [4]:
print("\nDataset Shape:\n")
df.shape

Dataset Shape:

(14, 10)

In [5]:
print("\nColumn Names:\n")
print(df.columns)

Column Names:

Index(['Name', 'Gender', 'Age', 'Department', 'Attendance', 'Study_Hours',
       'Assignment_Marks', 'Internal_Marks', 'Exam_Score', 'Result'],
      dtype='str')

In [6]:
print("\nCheck datatype:\n")
df.dtypes

Check datatype:

Name                    str
Gender                  str
Age                   int64
Department              str
Attendance          float64
Study_Hours         float64
Assignment_Marks      int64
Internal_Marks      float64
Exam_Score            int64
Result                  str
dtype: object

In [7]:
print("\nDescription Statistics:\n")
df.describe()

Description Statistics:

,Age,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score
count,14.000000,13.000000,14.000000,14.000000,12.000000,14.000000
mean,19.928571,81.769231,5.171429,15.428571,23.916667,72.714286
std,0.730046,11.705795,1.810409,3.005489,4.776045,17.098936
min,19.000000,60.000000,2.000000,10.000000,15.000000,41.000000
25%,19.250000,75.000000,4.125000,13.250000,20.750000,62.250000
50%,20.000000,85.000000,5.250000,16.000000,25.000000,75.000000
75%,20.000000,90.000000,6.725000,18.000000,28.000000,86.000000
max,21.000000,95.000000,7.500000,19.000000,29.000000,93.000000

In [8]:
print("\nStatistics of all columns:\n")
df.describe()

Statistics of all columns:

,Age,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score
count,14.000000,13.000000,14.000000,14.000000,12.000000,14.000000
mean,19.928571,81.769231,5.171429,15.428571,23.916667,72.714286
std,0.730046,11.705795,1.810409,3.005489,4.776045,17.098936
min,19.000000,60.000000,2.000000,10.000000,15.000000,41.000000
25%,19.250000,75.000000,4.125000,13.250000,20.750000,62.250000
50%,20.000000,85.000000,5.250000,16.000000,25.000000,75.000000
75%,20.000000,90.000000,6.725000,18.000000,28.000000,86.000000
max,21.000000,95.000000,7.500000,19.000000,29.000000,93.000000

In [9]:
print("\nMissing Values:\n")
print(df.isnull().sum())

Missing Values:

Name                0
Gender              0
Age                 0
Department          0
Attendance          1
Study_Hours         0
Assignment_Marks    0
Internal_Marks      2
Exam_Score          0
Result              0
dtype: int64

In [10]:
print("\nRows with missing values:\n")
df[df.isnull().any(axis=1)]

Rows with missing values:

,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score,Result
S_No,,,,,,,,,,
5,Anusha,Female,20,CSE,68.0,3.0,12,NaN,52,Pass
7,Karan,Male,20,ECE,NaN,4.0,13,20.0,61,Pass
11,Laalitya,Female,21,EEE,78.0,4.8,15,NaN,70,Pass

In [11]:
print("\nNumber of Duplicate Records:\n")
print(df.duplicated().sum())

Number of Duplicate Records:

2

In [12]:
print("\nDuplicate Records:\n")
df[df.duplicated()]

Duplicate Records:

,Name,Gender,Age,Department,Attendance,Study_Hours,Assignment_Marks,Internal_Marks,Exam_Score,Result
S_No,,,,,,,,,,
13,Likhita,Female,20,CSE,95.0,7.5,19,29.0,93,Pass
14,Anvi,Female,20,CSE,90.0,6.8,18,28.0,86,Pass

In [13]:
df=df.drop_duplicates()
print("Shape after removing duplicates:",df.shape)

Shape after removing duplicates: (12, 10)

In [14]:
df["Attendance"]=df["Attendance"].fillna(df["Attendance"].mean())
df["Internal_Marks"]=df["Internal_Marks"].fillna(df["Internal_Marks"].mean())
print("\nMissing Values after filling:\n")
print(df.isnull().sum())

Missing Values after filling:

Name                0
Gender              0
Age                 0
Department          0
Attendance          0
Study_Hours         0
Assignment_Marks    0
Internal_Marks      0
Exam_Score          0
Result              0
dtype: int64

In [15]:
print("\nAverage Exam Score by Department:\n")
df.groupby("Department")["Exam_Score"].mean()

Average Exam Score by Department:

Department
CSE    80.60
ECE    69.25
EEE    53.00
Name: Exam_Score, dtype: float64

In [16]:
print("\nAverage Exam Score by Gender:\n")
df.groupby("Gender")["Exam_Score"].mean()

Average Exam Score by Gender:

Gender
Female    77.875
Male      54.000
Name: Exam_Score, dtype: float64

In [17]:
print("\nPass and Fail count:\n")
df["Result"].value_counts()

Pass and Fail count:

Result
Pass    10
Fail     2
Name: count, dtype: int64